name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check-fmt:
    uses: ./.github/workflows/check-fmt.yml
    permissions:
      contents: read

  check-lint:
    uses: ./.github/workflows/check-lint.yml
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  check-zizmor:
    uses: ./.github/workflows/check-zizmor.yml
    permissions:
      contents: read
